# -*- coding: utf-8 -*-
"""Quiz_Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/101Jb3gMK_cObutA5y7s_N1MYHSufZNrd
"""

import random

def start_quiz():
    # List of questions in English
    questions = [
        {
            "prompt": "Which programming language is known as the language of AI?",
            "options": ["A) Java", "B) Python", "C) C++", "D) Ruby"],
            "answer": "B"
        },
        {
            "prompt": "What is the largest ocean on Earth?",
            "options": ["A) Atlantic", "B) Indian", "C) Arctic", "D) Pacific"],
            "answer": "D"
        },
        {
            "prompt": "Which element has the chemical symbol 'O'?",
            "options": ["A) Gold", "B) Oxygen", "C) Silver", "D) Iron"],
            "answer": "B"
        },
        {
            "prompt": "Who is the creator of Python?",
            "options": ["A) Bill Gates", "B) Mark Zuckerberg", "C) Guido van Rossum", "D) Elon Musk"],
            "answer": "C"
        },
        {
            "prompt": "What is 5 multiplied by 6?",
            "options": ["A) 11", "B) 30", "C) 25", "D) 35"],
            "answer": "B"
        }
    ]

    # Shuffle the questions to make it random
    random.shuffle(questions)

    score = 0
    total = len(questions)

    print("--- Welcome to the English Quiz Game! ---")
    print(f"Total Questions: {total}\n")

    for i, q in enumerate(questions, 1):
        print(f"Question {i}: {q['prompt']}")
        for option in q['options']:
            print(option)

        user_answer = input("Your answer (A, B, C, or D): ").strip().upper()

        if user_answer == q['answer']:
            print("Correct! ✅\n")
            score += 1
        else:
            print(f"Incorrect! ❌ The right answer was {q['answer']}.\n")

    print("--- Game Over ---")
    print(f"Your final score: {score} out of {total}")

    if score == total:
        print("Perfect! You are a genius! 🌟")
    elif score >= total / 2:
        print("Good job! You passed. 👍")
    else:
        print("Keep practicing! Better luck next time. 📚")

if __name__ == "__main__":
    start_quiz()